image: gcc
before_script:
 - apt-get update --yes
 - apt-get install --yes cmake
build-job:
  stage: build
  script:
    - mkdir ./calculator/build
    - cd ./calculator/build
    - cmake ..
    - make 

test-job1:
  stage: test
  script:
    - cd ./calculator/test/
    - make
    - ./testAll