image: registry.gitlab.com/maddyb99/cpp_docker:latest
# before_script:
#  - apt-get update --yes
#  - apt-get install --yes cmake
#  - apt-get install --yes libgtest-dev


build-job:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - mkdir ./cpp_calculator/build
    - cd ./cpp_calculator/build
    - cmake ..
    - make 

test-job1:
  stage: test
  script:
    - git submodule init
    - git submodule update
    - mkdir ./cpp_calculator/test/build
    - cd ./cpp_calculator/test/build
    - cmake ..
    - make 
    - ./CalculatorTest