image: gcc

build-job:
  stage: build
  script:
    - mkdir ./calculator/build
    - cd ./calculator/build
    - cmake ..
    - make 

test-job1:
  stage: test
  script:
    - mkdir ./calculator/test/build
    - cd ./calculator/test/build
    - cmake ..
    - make 
    - ./CalculatorTest